version: "3"

services:
  goproxy:
    restart: always
    image: lwch/goproxy
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: goproxy-data
        target: /tmp

volumes:
  goproxy-data:
